/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as IdxDataRouteImport } from './routes/idx-data'
import { Route as ForexRouteImport } from './routes/forex'
import { Route as FairValueRouteImport } from './routes/fair-value'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const IdxDataRoute = IdxDataRouteImport.update({
  id: '/idx-data',
  path: '/idx-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexRoute = ForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const FairValueRoute = FairValueRouteImport.update({
  id: '/fair-value',
  path: '/fair-value',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/crypto': typeof CryptoRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/crypto': typeof CryptoRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/crypto': typeof CryptoRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chart'
    | '/crypto'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/screener'
    | '/settings'
    | '/technical'
    | '/watchlist'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chart'
    | '/crypto'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/screener'
    | '/settings'
    | '/technical'
    | '/watchlist'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/chart'
    | '/crypto'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/screener'
    | '/settings'
    | '/technical'
    | '/watchlist'
    | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChartRoute: typeof ChartRoute
  CryptoRoute: typeof CryptoRoute
  EarningsRoute: typeof EarningsRoute
  FairValueRoute: typeof FairValueRoute
  ForexRoute: typeof ForexRoute
  IdxDataRoute: typeof IdxDataRoute
  InstitutionalRoute: typeof InstitutionalRoute
  NewsRoute: typeof NewsRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  TechnicalRoute: typeof TechnicalRoute
  WatchlistRoute: typeof WatchlistRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idx-data': {
      id: '/idx-data'
      path: '/idx-data'
      fullPath: '/idx-data'
      preLoaderRoute: typeof IdxDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex': {
      id: '/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof ForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-value': {
      id: '/fair-value'
      path: '/fair-value'
      fullPath: '/fair-value'
      preLoaderRoute: typeof FairValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChartRoute: ChartRoute,
  CryptoRoute: CryptoRoute,
  EarningsRoute: EarningsRoute,
  FairValueRoute: FairValueRoute,
  ForexRoute: ForexRoute,
  IdxDataRoute: IdxDataRoute,
  InstitutionalRoute: InstitutionalRoute,
  NewsRoute: NewsRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  TechnicalRoute: TechnicalRoute,
  WatchlistRoute: WatchlistRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
