/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as SmartMoneyRouteImport } from './routes/smart-money'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as IdxDataRouteImport } from './routes/idx-data'
import { Route as ForexRouteImport } from './routes/forex'
import { Route as FairValueRouteImport } from './routes/fair-value'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DividendsRouteImport } from './routes/dividends'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as CorporateEventsRouteImport } from './routes/corporate-events'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'
import { Route as SectorsSectorNameRouteImport } from './routes/sectors.$sectorName'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMoneyRoute = SmartMoneyRouteImport.update({
  id: '/smart-money',
  path: '/smart-money',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const IdxDataRoute = IdxDataRouteImport.update({
  id: '/idx-data',
  path: '/idx-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ForexRoute = ForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const FairValueRoute = FairValueRouteImport.update({
  id: '/fair-value',
  path: '/fair-value',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendsRoute = DividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateEventsRoute = CorporateEventsRouteImport.update({
  id: '/corporate-events',
  path: '/corporate-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorNameRoute = SectorsSectorNameRouteImport.update({
  id: '/$sectorName',
  path: '/$sectorName',
  getParentRoute: () => SectorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/crypto': typeof CryptoRoute
  '/dividends': typeof DividendsRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/sectors/$sectorName': typeof SectorsSectorNameRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/crypto': typeof CryptoRoute
  '/dividends': typeof DividendsRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/sectors/$sectorName': typeof SectorsSectorNameRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/crypto': typeof CryptoRoute
  '/dividends': typeof DividendsRoute
  '/earnings': typeof EarningsRoute
  '/fair-value': typeof FairValueRoute
  '/forex': typeof ForexRoute
  '/idx-data': typeof IdxDataRoute
  '/institutional': typeof InstitutionalRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/smart-money': typeof SmartMoneyRoute
  '/technical': typeof TechnicalRoute
  '/watchlist': typeof WatchlistRoute
  '/sectors/$sectorName': typeof SectorsSectorNameRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chart'
    | '/corporate-events'
    | '/crypto'
    | '/dividends'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/portfolio'
    | '/screener'
    | '/sectors'
    | '/settings'
    | '/smart-money'
    | '/technical'
    | '/watchlist'
    | '/sectors/$sectorName'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chart'
    | '/corporate-events'
    | '/crypto'
    | '/dividends'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/portfolio'
    | '/screener'
    | '/sectors'
    | '/settings'
    | '/smart-money'
    | '/technical'
    | '/watchlist'
    | '/sectors/$sectorName'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/chart'
    | '/corporate-events'
    | '/crypto'
    | '/dividends'
    | '/earnings'
    | '/fair-value'
    | '/forex'
    | '/idx-data'
    | '/institutional'
    | '/news'
    | '/portfolio'
    | '/screener'
    | '/sectors'
    | '/settings'
    | '/smart-money'
    | '/technical'
    | '/watchlist'
    | '/sectors/$sectorName'
    | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChartRoute: typeof ChartRoute
  CorporateEventsRoute: typeof CorporateEventsRoute
  CryptoRoute: typeof CryptoRoute
  DividendsRoute: typeof DividendsRoute
  EarningsRoute: typeof EarningsRoute
  FairValueRoute: typeof FairValueRoute
  ForexRoute: typeof ForexRoute
  IdxDataRoute: typeof IdxDataRoute
  InstitutionalRoute: typeof InstitutionalRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  ScreenerRoute: typeof ScreenerRoute
  SectorsRoute: typeof SectorsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SmartMoneyRoute: typeof SmartMoneyRoute
  TechnicalRoute: typeof TechnicalRoute
  WatchlistRoute: typeof WatchlistRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-money': {
      id: '/smart-money'
      path: '/smart-money'
      fullPath: '/smart-money'
      preLoaderRoute: typeof SmartMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idx-data': {
      id: '/idx-data'
      path: '/idx-data'
      fullPath: '/idx-data'
      preLoaderRoute: typeof IdxDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forex': {
      id: '/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof ForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-value': {
      id: '/fair-value'
      path: '/fair-value'
      fullPath: '/fair-value'
      preLoaderRoute: typeof FairValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividends': {
      id: '/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof DividendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-events': {
      id: '/corporate-events'
      path: '/corporate-events'
      fullPath: '/corporate-events'
      preLoaderRoute: typeof CorporateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sectorName': {
      id: '/sectors/$sectorName'
      path: '/$sectorName'
      fullPath: '/sectors/$sectorName'
      preLoaderRoute: typeof SectorsSectorNameRouteImport
      parentRoute: typeof SectorsRoute
    }
  }
}

interface SectorsRouteChildren {
  SectorsSectorNameRoute: typeof SectorsSectorNameRoute
}

const SectorsRouteChildren: SectorsRouteChildren = {
  SectorsSectorNameRoute: SectorsSectorNameRoute,
}

const SectorsRouteWithChildren =
  SectorsRoute._addFileChildren(SectorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChartRoute: ChartRoute,
  CorporateEventsRoute: CorporateEventsRoute,
  CryptoRoute: CryptoRoute,
  DividendsRoute: DividendsRoute,
  EarningsRoute: EarningsRoute,
  FairValueRoute: FairValueRoute,
  ForexRoute: ForexRoute,
  IdxDataRoute: IdxDataRoute,
  InstitutionalRoute: InstitutionalRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  ScreenerRoute: ScreenerRoute,
  SectorsRoute: SectorsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SmartMoneyRoute: SmartMoneyRoute,
  TechnicalRoute: TechnicalRoute,
  WatchlistRoute: WatchlistRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
